# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "HOME"
  url = "/"
  weight = 10

[[main]]
  name = "RESEARCH"
  url = "research/"
  weight = 20

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 30

[[main]]
  name = "TEACHING"
  url = "teaching/"
  weight = 40

[[main]]
  name = "CONTACT"
  url = "contact/"
  weight = 50

# [[main]]
#    name = "GOOGLE SCHOLAR"
#    url = "https://scholar.google.com/citations?user=xPSRkX4AAAAJ"
#    weight = 60

# [[main]]
#    name = "DATAVERSE"
#    url = "https://dataverse.harvard.edu/dataverse/areeves"
#    weight = 70

 [[main]]
    name = "IN THE NEWS"
    url = "news/"
    weight = 80
